// Package deck turns text a parent pasted into flashcards, and stores the
// ones a human approves.
//
// A generated Card is transient — it travels back to the client, which holds
// it until the parent reviews it (accept / edit / reject). The kept cards are
// saved into a Deck — a named set of cards owned by a profile — via Store.
package deck

import (
	"errors"
	"time"
)

// ErrProfileNotFound is returned by Store.Create when the target profile does
// not exist or does not belong to the requesting user. The two cases are not
// distinguished on purpose: revealing that someone else's profile exists is a
// leak.
var ErrProfileNotFound = errors.New("profile not found")

// Card is one flashcard's content — as generated by the model, or on its way
// into a Deck. It carries no identity: a Card only becomes a row once saved.
type Card struct {
	Question string
	Answer   string
}

// Deck is a named set of cards owned by a profile.
type Deck struct {
	ID        int64
	ProfileID int64
	Name      string
	CreatedAt time.Time
}
