name: ${PROJECT_CODENAME}

services:
  api:
    build:
      context: ../api
      dockerfile: ../docker/Dockerfile.api
      args:
        GO_VERSION: ${GO_VERSION}
        AIR_VERSION: ${AIR_VERSION}
    container_name: ${PROJECT_CODENAME}-api
    networks:
      - public
      - private

  web:
    build:
      context: ../web
      dockerfile: ../docker/Dockerfile.web
      args:
        BUN_VERSION: ${BUN_VERSION}
    container_name: ${PROJECT_CODENAME}-web
    networks:
      - public

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${PROJECT_CODENAME}-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # TODO (prod): migrate to Docker secrets (POSTGRES_PASSWORD_FILE)
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - private
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  caddy:
    image: caddy:${CADDY_VERSION}-alpine
    container_name: ${PROJECT_CODENAME}-caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
      - ACME_EMAIL=${ACME_EMAIL}
    networks:
      - public

networks:
  public:
  private:

volumes:
  pgdata:
  web_dist:
  caddy_data:
  caddy_config:
