services:
  api:
    build:
      target: prod
      platforms:
        - linux/amd64
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      target: prod
      platforms:
        - linux/amd64
    volumes:
      - web_dist:/srv
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    restart: "no"

  postgres:
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  caddy:
    volumes:
      - ./caddy/frontend.prod.caddy:/etc/caddy/frontend.caddy:ro
      - web_dist:/srv:ro
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
      web:
        condition: service_completed_successfully

volumes:
  web_dist:
