/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhoRouteImport } from './routes/_authenticated/who'
import { Route as AuthenticatedTrainRouteImport } from './routes/_authenticated/train'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedCreateIndexRouteImport } from './routes/_authenticated/create/index'
import { Route as AuthenticatedProfilesNewRouteImport } from './routes/_authenticated/profiles/new'
import { Route as AuthenticatedCreateReviewRouteImport } from './routes/_authenticated/create/review'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhoRoute = AuthenticatedWhoRouteImport.update({
  id: '/who',
  path: '/who',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainRoute = AuthenticatedTrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateIndexRoute =
  AuthenticatedCreateIndexRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilesNewRoute =
  AuthenticatedProfilesNewRouteImport.update({
    id: '/profiles/new',
    path: '/profiles/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreateReviewRoute =
  AuthenticatedCreateReviewRouteImport.update({
    id: '/create/review',
    path: '/create/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/account': typeof AuthenticatedAccountRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/train': typeof AuthenticatedTrainRoute
  '/who': typeof AuthenticatedWhoRoute
  '/create/review': typeof AuthenticatedCreateReviewRoute
  '/profiles/new': typeof AuthenticatedProfilesNewRoute
  '/create/': typeof AuthenticatedCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/account': typeof AuthenticatedAccountRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/train': typeof AuthenticatedTrainRoute
  '/who': typeof AuthenticatedWhoRoute
  '/create/review': typeof AuthenticatedCreateReviewRoute
  '/profiles/new': typeof AuthenticatedProfilesNewRoute
  '/create': typeof AuthenticatedCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/train': typeof AuthenticatedTrainRoute
  '/_authenticated/who': typeof AuthenticatedWhoRoute
  '/_authenticated/create/review': typeof AuthenticatedCreateReviewRoute
  '/_authenticated/profiles/new': typeof AuthenticatedProfilesNewRoute
  '/_authenticated/create/': typeof AuthenticatedCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/welcome'
    | '/account'
    | '/learn'
    | '/onboarding'
    | '/train'
    | '/who'
    | '/create/review'
    | '/profiles/new'
    | '/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/welcome'
    | '/account'
    | '/learn'
    | '/onboarding'
    | '/train'
    | '/who'
    | '/create/review'
    | '/profiles/new'
    | '/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/welcome'
    | '/_authenticated/account'
    | '/_authenticated/learn'
    | '/_authenticated/onboarding'
    | '/_authenticated/train'
    | '/_authenticated/who'
    | '/_authenticated/create/review'
    | '/_authenticated/profiles/new'
    | '/_authenticated/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/who': {
      id: '/_authenticated/who'
      path: '/who'
      fullPath: '/who'
      preLoaderRoute: typeof AuthenticatedWhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/train': {
      id: '/_authenticated/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof AuthenticatedTrainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create/': {
      id: '/_authenticated/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof AuthenticatedCreateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiles/new': {
      id: '/_authenticated/profiles/new'
      path: '/profiles/new'
      fullPath: '/profiles/new'
      preLoaderRoute: typeof AuthenticatedProfilesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create/review': {
      id: '/_authenticated/create/review'
      path: '/create/review'
      fullPath: '/create/review'
      preLoaderRoute: typeof AuthenticatedCreateReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedTrainRoute: typeof AuthenticatedTrainRoute
  AuthenticatedWhoRoute: typeof AuthenticatedWhoRoute
  AuthenticatedCreateReviewRoute: typeof AuthenticatedCreateReviewRoute
  AuthenticatedProfilesNewRoute: typeof AuthenticatedProfilesNewRoute
  AuthenticatedCreateIndexRoute: typeof AuthenticatedCreateIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedTrainRoute: AuthenticatedTrainRoute,
  AuthenticatedWhoRoute: AuthenticatedWhoRoute,
  AuthenticatedCreateReviewRoute: AuthenticatedCreateReviewRoute,
  AuthenticatedProfilesNewRoute: AuthenticatedProfilesNewRoute,
  AuthenticatedCreateIndexRoute: AuthenticatedCreateIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
