/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as PaywallRouteImport } from "./routes/paywall"
import { Route as HomeRouteImport } from "./routes/home"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ChildIndexRouteImport } from "./routes/child/index"
import { Route as OnboardingFirstDeckRouteImport } from "./routes/onboarding/first-deck"
import { Route as OnboardingCreateProfileRouteImport } from "./routes/onboarding/create-profile"
import { Route as OnboardingAccountTypeRouteImport } from "./routes/onboarding/account-type"
import { Route as DecksNewRouteImport } from "./routes/decks/new"
import { Route as DecksIdFilterRouteImport } from "./routes/decks/$id/filter"
import { Route as ChildReviewDeckIdIndexRouteImport } from "./routes/child/review/$deckId/index"
import { Route as ChildReviewDeckIdResultRouteImport } from "./routes/child/review/$deckId/result"

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: "/paywall",
  path: "/paywall",
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ChildIndexRoute = ChildIndexRouteImport.update({
  id: "/child/",
  path: "/child/",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFirstDeckRoute = OnboardingFirstDeckRouteImport.update({
  id: "/onboarding/first-deck",
  path: "/onboarding/first-deck",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCreateProfileRoute = OnboardingCreateProfileRouteImport.update({
  id: "/onboarding/create-profile",
  path: "/onboarding/create-profile",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAccountTypeRoute = OnboardingAccountTypeRouteImport.update({
  id: "/onboarding/account-type",
  path: "/onboarding/account-type",
  getParentRoute: () => rootRouteImport,
} as any)
const DecksNewRoute = DecksNewRouteImport.update({
  id: "/decks/new",
  path: "/decks/new",
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIdFilterRoute = DecksIdFilterRouteImport.update({
  id: "/decks/$id/filter",
  path: "/decks/$id/filter",
  getParentRoute: () => rootRouteImport,
} as any)
const ChildReviewDeckIdIndexRoute = ChildReviewDeckIdIndexRouteImport.update({
  id: "/child/review/$deckId/",
  path: "/child/review/$deckId/",
  getParentRoute: () => rootRouteImport,
} as any)
const ChildReviewDeckIdResultRoute = ChildReviewDeckIdResultRouteImport.update({
  id: "/child/review/$deckId/result",
  path: "/child/review/$deckId/result",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/home": typeof HomeRoute
  "/paywall": typeof PaywallRoute
  "/settings": typeof SettingsRoute
  "/decks/new": typeof DecksNewRoute
  "/onboarding/account-type": typeof OnboardingAccountTypeRoute
  "/onboarding/create-profile": typeof OnboardingCreateProfileRoute
  "/onboarding/first-deck": typeof OnboardingFirstDeckRoute
  "/child/": typeof ChildIndexRoute
  "/decks/$id/filter": typeof DecksIdFilterRoute
  "/child/review/$deckId/result": typeof ChildReviewDeckIdResultRoute
  "/child/review/$deckId/": typeof ChildReviewDeckIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/home": typeof HomeRoute
  "/paywall": typeof PaywallRoute
  "/settings": typeof SettingsRoute
  "/decks/new": typeof DecksNewRoute
  "/onboarding/account-type": typeof OnboardingAccountTypeRoute
  "/onboarding/create-profile": typeof OnboardingCreateProfileRoute
  "/onboarding/first-deck": typeof OnboardingFirstDeckRoute
  "/child": typeof ChildIndexRoute
  "/decks/$id/filter": typeof DecksIdFilterRoute
  "/child/review/$deckId/result": typeof ChildReviewDeckIdResultRoute
  "/child/review/$deckId": typeof ChildReviewDeckIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/home": typeof HomeRoute
  "/paywall": typeof PaywallRoute
  "/settings": typeof SettingsRoute
  "/decks/new": typeof DecksNewRoute
  "/onboarding/account-type": typeof OnboardingAccountTypeRoute
  "/onboarding/create-profile": typeof OnboardingCreateProfileRoute
  "/onboarding/first-deck": typeof OnboardingFirstDeckRoute
  "/child/": typeof ChildIndexRoute
  "/decks/$id/filter": typeof DecksIdFilterRoute
  "/child/review/$deckId/result": typeof ChildReviewDeckIdResultRoute
  "/child/review/$deckId/": typeof ChildReviewDeckIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/home"
    | "/paywall"
    | "/settings"
    | "/decks/new"
    | "/onboarding/account-type"
    | "/onboarding/create-profile"
    | "/onboarding/first-deck"
    | "/child/"
    | "/decks/$id/filter"
    | "/child/review/$deckId/result"
    | "/child/review/$deckId/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/home"
    | "/paywall"
    | "/settings"
    | "/decks/new"
    | "/onboarding/account-type"
    | "/onboarding/create-profile"
    | "/onboarding/first-deck"
    | "/child"
    | "/decks/$id/filter"
    | "/child/review/$deckId/result"
    | "/child/review/$deckId"
  id:
    | "__root__"
    | "/"
    | "/home"
    | "/paywall"
    | "/settings"
    | "/decks/new"
    | "/onboarding/account-type"
    | "/onboarding/create-profile"
    | "/onboarding/first-deck"
    | "/child/"
    | "/decks/$id/filter"
    | "/child/review/$deckId/result"
    | "/child/review/$deckId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  PaywallRoute: typeof PaywallRoute
  SettingsRoute: typeof SettingsRoute
  DecksNewRoute: typeof DecksNewRoute
  OnboardingAccountTypeRoute: typeof OnboardingAccountTypeRoute
  OnboardingCreateProfileRoute: typeof OnboardingCreateProfileRoute
  OnboardingFirstDeckRoute: typeof OnboardingFirstDeckRoute
  ChildIndexRoute: typeof ChildIndexRoute
  DecksIdFilterRoute: typeof DecksIdFilterRoute
  ChildReviewDeckIdResultRoute: typeof ChildReviewDeckIdResultRoute
  ChildReviewDeckIdIndexRoute: typeof ChildReviewDeckIdIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/paywall": {
      id: "/paywall"
      path: "/paywall"
      fullPath: "/paywall"
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/home": {
      id: "/home"
      path: "/home"
      fullPath: "/home"
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/child/": {
      id: "/child/"
      path: "/child"
      fullPath: "/child/"
      preLoaderRoute: typeof ChildIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding/first-deck": {
      id: "/onboarding/first-deck"
      path: "/onboarding/first-deck"
      fullPath: "/onboarding/first-deck"
      preLoaderRoute: typeof OnboardingFirstDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding/create-profile": {
      id: "/onboarding/create-profile"
      path: "/onboarding/create-profile"
      fullPath: "/onboarding/create-profile"
      preLoaderRoute: typeof OnboardingCreateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding/account-type": {
      id: "/onboarding/account-type"
      path: "/onboarding/account-type"
      fullPath: "/onboarding/account-type"
      preLoaderRoute: typeof OnboardingAccountTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decks/new": {
      id: "/decks/new"
      path: "/decks/new"
      fullPath: "/decks/new"
      preLoaderRoute: typeof DecksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decks/$id/filter": {
      id: "/decks/$id/filter"
      path: "/decks/$id/filter"
      fullPath: "/decks/$id/filter"
      preLoaderRoute: typeof DecksIdFilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/child/review/$deckId/": {
      id: "/child/review/$deckId/"
      path: "/child/review/$deckId"
      fullPath: "/child/review/$deckId/"
      preLoaderRoute: typeof ChildReviewDeckIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/child/review/$deckId/result": {
      id: "/child/review/$deckId/result"
      path: "/child/review/$deckId/result"
      fullPath: "/child/review/$deckId/result"
      preLoaderRoute: typeof ChildReviewDeckIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  PaywallRoute: PaywallRoute,
  SettingsRoute: SettingsRoute,
  DecksNewRoute: DecksNewRoute,
  OnboardingAccountTypeRoute: OnboardingAccountTypeRoute,
  OnboardingCreateProfileRoute: OnboardingCreateProfileRoute,
  OnboardingFirstDeckRoute: OnboardingFirstDeckRoute,
  ChildIndexRoute: ChildIndexRoute,
  DecksIdFilterRoute: DecksIdFilterRoute,
  ChildReviewDeckIdResultRoute: ChildReviewDeckIdResultRoute,
  ChildReviewDeckIdIndexRoute: ChildReviewDeckIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
